apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: broker-proxy
  namespace: ledhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      name: proxy
      labels:
        app: proxy
    spec:
      volumes:
        - name: service-account
          secret:
           secretName: proxy-to-local-publisher
      containers:
        - name: proxy
          image: us.gcr.io/n3wscott-ledhouse-demo/k8s-broker-proxy:1589f8d
          volumeMounts:
            - name: service-account
              mountPath: /var/secrets/service-account
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/service-account/privateKeyData
            - name: GOOGLE_CLOUD_PROJECT
              valueFrom:
                secretKeyRef:
                  name: proxy-to-local-publisher
                  key: projectId
            - name: PUBSUB_TOPIC
              valueFrom:
                secretKeyRef:
                  name: proxy-to-local-publisher
                  key: topicId
            - name: PUBSUB_SUBSCRIPTION
              valueFrom:
                secretKeyRef:
                  name: local-to-proxy-subscriber
                  key: subscriptionId
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: ledhouse
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: proxy
spec:
  selector:
    app: proxy
  ports:
  - port: 3000
    targetPort: 8080
  type: LoadBalancer
