#!/bin/bash

svcat unbind 1a-blue
svcat unbind 1a-green
svcat unbind 1a-red
svcat unbind 1b-blue
svcat unbind 1b-green
svcat unbind 1b-red
svcat unbind 1c-blue
svcat unbind 1c-green
svcat unbind 1c-red
svcat unbind 2a-blue
svcat unbind 2a-green
svcat unbind 2a-red
svcat unbind 2b-blue
svcat unbind 2b-green
svcat unbind 2b-red
svcat unbind 2c-blue
svcat unbind 2c-green
svcat unbind 2c-red
svcat unbind 3a-blue
svcat unbind 3a-green
svcat unbind 3a-red
svcat unbind 3b-blue
svcat unbind 3b-green
svcat unbind 3b-red
svcat unbind 3c-blue
svcat unbind 3c-green
svcat unbind 3c-red
svcat unbind 4a-blue
svcat unbind 4a-green
svcat unbind 4a-red